# Generated by Django 4.1.2 on 2022-11-02 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('inscriptionNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('familyName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('birthDate', models.DateField(default=datetime.date(2003, 1, 1))),
                ('photo', models.ImageField(max_length=200, upload_to='photos/students')),
                ('stdGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_app.group', verbose_name='student Groupe')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
