# Generated by Django 4.1.2 on 2022-11-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('FirstClass', 'first_class'), ('SecondClass', 'second_class')], default='FirstClass', max_length=100),
        ),
    ]
